"""migrate

Revision ID: 9193d0072363
Revises: 
Create Date: 2024-01-05 15:29:36.690116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9193d0072363'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('file', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buku',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('judulbuku', sa.String(length=100), nullable=False),
    sa.Column('pengarang', sa.String(length=100), nullable=False),
    sa.Column('penerbit', sa.String(length=100), nullable=False),
    sa.Column('tahunterbit', sa.String(length=100), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=False),
    sa.Column('pdf', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tipe', sa.String(length=100), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('tempatlahir', sa.String(length=100), nullable=False),
    sa.Column('tanggallahir', sa.DateTime(), nullable=True),
    sa.Column('jeniskelamin', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('alamat', sa.String(length=100), nullable=False),
    sa.Column('pekerjaan', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pinjam',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('idbuku', sa.BigInteger(), nullable=False),
    sa.Column('idmember', sa.BigInteger(), nullable=False),
    sa.Column('tanggalpinjam', sa.DateTime(), nullable=True),
    sa.Column('tanggalkembali', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idbuku'], ['buku.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idmember'], ['member.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pinjam')
    op.drop_table('member')
    op.drop_table('buku')
    op.drop_table('admin')
    # ### end Alembic commands ###
